version: "2"
services:
  wallet-service:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wallet-service
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
